-- Baseline schema for Safe Space COYS

create table if not exists public.mood_entries (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    emotion text not null,
    intensity int not null check (intensity between 1 and 10),
    trigger text,
    created_at timestamptz not null default now()
);

create table if not exists public.posts (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    content text not null,
    post_type text not null,
    category text,
    created_at timestamptz not null default now()
);

create index if not exists mood_entries_user_id_idx on public.mood_entries (user_id);
create index if not exists posts_user_id_idx on public.posts (user_id);
create index if not exists posts_type_idx on public.posts (post_type);
